In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('bangladesh_student_performance_updated.csv')

In [3]:
df.shape

(2018, 16)

In [4]:
df.sample(10)

,date,gender,age,address,famsize,Pstatus,M_Edu,F_Edu,M_Job,F_Job,relationship,smoker,tuition_fee,time_friends,ssc_result,hsc_result
445,29/04/2018,F,17.0,Urban,GT3,Together,1,1,Services,Teacher,Yes,No,100858.0,4,3.50,2.69
1079,29/04/2018,F,17.0,Urban,LE3,Together,3,3,Teacher,Teacher,Yes,No,80561.0,5,3.08,2.54
689,29/04/2018,M,18.0,Rural,GT3,Together,2,2,Health,Services,Yes,No,35360.0,1,3.14,2.57
1008,29/04/2018,M,18.0,Urban,GT3,Together,1,2,At_home,Business,No,No,76959.0,3,3.52,2.84
1926,29/04/2018,F,17.0,Urban,GT3,Together,2,4,Services,Farmer,No,Yes,116349.0,3,4.25,3.67
149,29/04/2018,M,19.0,Rural,GT3,Together,4,1,At_home,Farmer,No,No,71028.0,3,3.75,3.19
38,29/04/2018,F,17.0,Rural,GT3,Together,3,1,Teacher,Farmer,No,No,55032.0,4,3.18,2.56
1443,29/04/2018,M,19.0,Rural,LE3,Together,3,3,Services,Farmer,No,No,51071.0,5,4.08,3.59
1984,29/04/2018,M,NaN,Rural,GT3,Together,0,1,Health,Health,Yes,No,43313.0,5,4.18,3.21
512,29/04/2018,F,19.0,Rural,GT3,Together,3,2,At_home,Health,No,No,59198.0,1,3.82,3.52

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2018 entries, 0 to 2017
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          2018 non-null   object
 1   gender        2018 non-null   object
 2   age           1983 non-null   float64
 3   address       1983 non-null   object
 4   famsize       2018 non-null   object
 5   Pstatus       2018 non-null   object
 6   M_Edu         2018 non-null   int64
 7   F_Edu         2018 non-null   int64
 8   M_Job         1983 non-null   object
 9   F_Job         2018 non-null   object
 10  relationship  2018 non-null   object
 11  smoker        2018 non-null   object
 12  tuition_fee   1983 non-null   float64
 13  time_friends  2018 non-null   int64
 14  ssc_result    2018 non-null   float64
 15  hsc_result    2018 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 252.4+ KB

In [8]:
df['time_friends'].unique()
df['M_Edu'].unique()
df['famsize'].unique()

array(['GT3', 'LE3'], dtype=object)

In [10]:
df.isnull().sum()

date             0
gender           0
age             35
address         35
famsize          0
Pstatus          0
M_Edu            0
F_Edu            0
M_Job           35
F_Job            0
relationship     0
smoker           0
tuition_fee     35
time_friends     0
ssc_result       0
hsc_result       0
dtype: int64

In [11]:
df.describe()

,age,M_Edu,F_Edu,tuition_fee,time_friends,ssc_result,hsc_result
count,1983.000000,2018.000000,2018.000000,1983.000000,2018.00000,2018.000000,2018.000000
mean,17.980837,1.871160,2.174430,73045.274332,3.05996,3.788087,3.199177
std,0.825695,1.194206,1.252979,24102.016020,1.43919,0.622376,0.604526
min,17.000000,0.000000,0.000000,25102.000000,1.00000,2.000000,2.000000
25%,17.000000,1.000000,1.000000,53639.500000,2.00000,3.360000,2.780000
50%,18.000000,2.000000,2.000000,71343.000000,3.00000,3.770000,3.160000
75%,19.000000,3.000000,3.000000,91185.000000,4.00000,4.230000,3.580000
max,19.000000,4.000000,4.000000,129168.000000,5.00000,5.000000,5.000000

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace=True)